### ISSUE TITLE
Implement a custom status line

### ISSUE THREAD

**Issue by FoxySeta** [lucat1/visimp#1]
https://github.com/itchyny/lightline.vim

**Comment by lucat1** [comment]
The statusline will be built in-house to allow the needed amount of modularity and a tight integration with the layers system.
Also there are way too many statusline alternatives, no choice would be fair and supporting every line anybody wants would be too much of an hassle.

This will take some more time compared to others.

**Comment by lucat1** [comment]
Closed in #33
