### ISSUE TITLE
Agda support

### ISSUE THREAD

**Issue by foxyseta** [lucat1/visimp#18]
Language server to be added to Mason:

- [ ] https://github.com/mason-org/mason-registry/issues/3936

Treesitter grammar: https://github.com/tree-sitter/tree-sitter-agda

**Comment by foxyseta** [comment]
Added the treesitter grammar. The LS is available on Mason.

**Comment by lucat1** [comment]
We can move forward with this one! the treesitter grammar is packaged in nvim-treesitter and the LSP is in Mason.
It's just a matter of creating a visimp layer (you can easily use the Go layer as an example).
