### ISSUE TITLE
Treesitter/highlighter error

### ISSUE THREAD

**Issue by kocierik** [lucat1/visimp#36]
Is there any fix? All the package are updated. 
- NVIM v0.6.0

If I run :checkhealth on vim, I've this particular error in this section --> lspconfig: require("lspconfig.health").check()

========================================================================
- `ERROR: sumneko_lua: The given command "/Users/kocierik/.local/share/nvim/lsp_servers/sumneko_lua/extension/server/bin/lua-language-server" is not executable.`

Here you can see all the log of vim checkhealth
- https://pastebin.com/dKzPRWhG

<img width="1158" alt="Screenshot 2021-12-26 at 11 15 00" src="https://user-images.githubusercontent.com/41591336/147405171-395e553b-9bfa-49e1-a8a3-5d5248194e25.png">

**Comment by lucat1** [comment]
I see two issues here:
1. The sumneko lua lsp is not executable (for some reason) and I'd suggest trying to uninstall it to solve the issue or disable the language (or its lsp) if not required.
2. The more interesting one: treesitter/highlight errors popping up everywhere. Now I can't reproduce this on my system after updating everything (please do both `:PakUpdate` and `:TSUpdate`). There is an open issue(nvim-treesitter/nvim-treesitter#1201) on treesitter's page but they don't seem to know the cause just yet.

If I was able to reproduce this issue I could certainly help more (I suspect a qiuck `:TSUpdate` may solve though).

**Comment by lucat1** [comment]
I also have encountered the first issue with `sumneko` lua lsp and a quick `:LspInstallerInfo` and hitting `u` on the sumneko entry fixes the thing (basically updates the language server).
As for the second issue, I cannot reproduce it. I may also suggest trying neovim's nighly version (see how to install it on macos with homebrew).

**Comment by kocierik** [comment]
thanks everything seems to work now!

**Comment by lucat1** [comment]
I believe the issue was upstream then and they fixed it.
