### ISSUE TITLE
Grammarly layer

### ISSUE THREAD

**Issue by FoxySeta** [lucat1/visimp#39]
A [Grammarly language server](https://github.com/znck/grammarly) for markdown is already available in [`lspinstaller`](https://github.com/williamboman/nvim-lsp-installer). Please note that Grammarly does not feature exclusively spellchecking, and thus cannot be (entirely) replaced by vim's most used spellchecking tools.

**Comment by lucat1** [comment]
Done in a6b1cf60f1369e49a3fd9af7a71afca3958298e2 but the LSP seems outdated (at least the one installed by `nvim-lsp-installer`). The this is: `nvim-lsp-installer` is out of date so I won't be expecting them to update the LSP download link to a maintained version. I'm currently in the process of moving `visimp` from `nvim-lsp-installer` to `mason.nvim`, its successor.

**Comment by lucat1** [comment]
Closed in #42
