### ISSUE TITLE
Coq support

### ISSUE THREAD

**Issue by foxyseta** [lucat1/visimp#49]
LSP (experimental): https://github.com/tomtomjhj/coq-lsp.nvim. Allows us to avoid using https://github.com/whonore/Coqtail
Formatter: `coqc -beautify`
Tree-sitter grammar: not out there yet?

**Comment by lucat1** [comment]
I’ll add it later today

**Comment by lucat1** [comment]
I think we can consider this closed with b9a6904. It does not use an LSP (but given the type of "language" I also don't think that an LSP is really appropriate. coqtail works fine tbh).
