### ISSUE TITLE
:wq

### ISSUE THREAD

**Issue by foxyseta** [lucat1/visimp#53]
Error message on `:wq`.
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'formatting_seq_sync' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

**Comment by foxyseta** [comment]
Solved by 2551feac3940e0c8bc3ce2c4f3c58fc0cf98a6df.

**Comment by specialfish9** [comment]
Hi, how did you solved?

**Comment by lucat1** [comment]
Mh, we should have added the autocommand provided here (@foxyseta changed from the old command to the new one):
https://github.com/lukas-reineke/lsp-format.nvim#wq-will-not-format-when-not-using-sync

Is this not working for you? (it is for me) if so, give me your nvim version and also the output of:
` cd ~/.local/share/nvim/site/pack/paks/start/visimp && git rev-parse HEAD`

**Comment by specialfish9** [comment]
The command outputs
`47305db32780288c96715e9f072de9150b997a38`
My nvim version is 0.9.1


Thanks!
