### ISSUE TITLE
Prolog support

### ISSUE THREAD

**Issue by foxyseta** [lucat1/visimp#56]
LSP server to be added to Mason:
- [ ] https://github.com/mason-org/mason-registry/issues/3935

Treesitter parser: https://github.com/Rukiza/tree-sitter-prolog (queries are being written in https://github.com/Rukiza/tree-sitter-prolog-queries. Waiting for them to be
- [ ] accepted by nvim-treesitter).

**Comment by lucat1** [comment]
Again, are you able to do this yourself?

**Comment by foxyseta** [comment]
Sure. I'll let you know when I have something ready.

**Comment by foxyseta** [comment]
Added a new tresitter parses. It is being actively developed.

**Comment by lucat1** [comment]
Like #59 this issue is blocked until the guys over at nvim-treesitter add support for the grammar.
For the LSP I believe we can just install the package and require it, even though it is not on Mason.
