### ISSUE TITLE
Typst language support

### ISSUE THREAD

**Issue by foxyseta** [lucat1/visimp#59]
LSP server: https://mason-registry.dev/registry/list#typst-lsp
Treesitter parser: https://github.com/uben0/tree-sitter-typst (better than the alternatives, someone is working on queries https://github.com/Nagefire/nvim-treesitter
- [ ] to add it to nvim-treesitter)

Preview: https://github.com/chomosuke/typst-preview.nvim

**Comment by lucat1** [comment]
Treesitter should do for the syntax highlighting

**Comment by foxyseta** [comment]
Added new treesitter parser. This one is being actively developed and has queries too.

**Comment by lucat1** [comment]
This parser seems promising, but we can't use it until [nvim-treesitter/nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) adds support for it.
Relevant: nvim-treesitter/nvim-treesitter#2282, nvim-treesitter/nvim-treesitter#5620
