### ISSUE TITLE
Rainbow delimiters via Treesitter

### ISSUE THREAD

**Issue by foxyseta** [lucat1/visimp#74]
Plugin:

https://gitlab.com/HiPhish/rainbow-delimiters.nvim

Only so many languages are supported:

https://gitlab.com/HiPhish/rainbow-delimiters.nvim/-/tree/master/queries?ref_type=heads

Should such a layer be called "delimiters"? "Rainbow"? Should it be enabled by default?

**Comment by lucat1** [comment]
1. Use the github repo, the plugin manager (like most for vim) are hardcoded with github's url for package sources
2. for the name I'd go with "rainbow"
3. I think it's fine to enable it by default yeah
