### ISSUE TITLE
Integrate rainbow-delimiters with blankline

### ISSUE THREAD

**Issue by lucat1** [lucat1/visimp#93]
Blankline supports an integration with rainbow-delimiter where the blankline uses the same color as the current delimiter level. The blankline layer should check if the rainbow-delimiter layer is enabled (for an example see layers which check if the lsp is enabled) and then integrate into it following: https://github.com/lukas-reineke/indent-blankline.nvim?tab=readme-ov-file#rainbow-delimitersnvim-integration

**Comment by foxyseta** [comment]
Will work on this as soon as Neovim 0.10 is released on Alpine and I can locally test this on my setup w/o indent-blanking breaking on startup (https://github.com/lukas-reineke/indent-blankline.nvim/issues/876).

**Comment by foxyseta** [comment]
> (for an example see layers which check if the lsp is enabled)

sorry, could not find any

**Comment by lucat1** [comment]
Yeah sorry, I wasn't really clear in my comment. What I think should be implemented is something akin to what the cmp layer does. Look at all the `if L.config.lsp` branches basically. This should be an option which declares whether rainbow delimiters should depend on blankline. In cmp the value is set to true by default (I don't necessarily have anything against that) but it could also be dynamically determined by checking if blankline is enabled by default (there's a method in loader for that).
